export const actionType = {
    SETTING_HEAD:'SETTING_HEAD',
    SETTING_USER_NAME:'SETTING_USER_NAME',
    SEND_EMOJI:'SEND_EMOJI',
    SEND_FAV_EMOJI:'SEND_FAV_EMOJI',
    SEND_IMAGE:'SEND_IMAGE',
    SEND_MUSIC:'SEND_MUSIC',
    CREATE_ROOM:'CREATE_ROOM',
    JOIN_ROOM:'JOIN_ROOM',
    Login:'LOGIN',
    SETTING_USER_DATA:'SETTING_USER_DATA',
}