export const actionType = {
    SETTING_HEAD:'SETTING_HEAD',
    SETTING_NAME:'SETTING_NAME',
    SEND_EMOJI:'SEND_EMOJI',
    SEND_FAV_EMOJI:'SEND_FAV_EMOJI',
    SEND_IMAGE:'SEND_IMAGE',
    SEND_MUSIC:'SEND_MUSIC',
}